# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kennith Leung
email: kennith@github.com
description: > # this means to ignore newlines until "baseurl:"
  Father, husband, write code, play basketball. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kennith.github.com" # the base hostname & protocol for your site
twitter_username: kennith
github_username:  kennith

# Build settings
markdown: kramdown

exclude: ['gulpfile.js', 'node_modules', 'package.json', 'README.md']
